// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;

namespace Microsoft.ML.Probabilistic.Learners.BayesPointMachineClassifierInternal
{
	public partial class CompoundSparseBinaryBpmTrainingEvidence_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12 has executed. Set this to false to force re-execution of Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12</summary>
		public bool Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone;
		/// <summary>True if Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11 has executed. Set this to false to force re-execution of Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11</summary>
		public bool Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isDone;
		/// <summary>True if Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11 has performed initialisation. Set this to false to force re-execution of Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11</summary>
		public bool Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isInitialised;
		/// <summary>True if Changed_FeatureCount has executed. Set this to false to force re-execution of Changed_FeatureCount</summary>
		public bool Changed_FeatureCount_isDone;
		/// <summary>True if Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2 has executed. Set this to false to force re-execution of Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2</summary>
		public bool Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isDone;
		/// <summary>True if Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2 has performed initialisation. Set this to false to force re-execution of Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2</summary>
		public bool Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised;
		/// <summary>True if Changed_FeatureCount_WeightConstraints has executed. Set this to false to force re-execution of Changed_FeatureCount_WeightConstraints</summary>
		public bool Changed_FeatureCount_WeightConstraints_isDone;
		/// <summary>True if Changed_FeatureCount_WeightPrecisionRateConstraints has executed. Set this to false to force re-execution of Changed_FeatureCount_WeightPrecisionRateConstraints</summary>
		public bool Changed_FeatureCount_WeightPrecisionRateConstraints_isDone;
		/// <summary>True if Changed_FeatureCount_ZeroFeatureValueInstanceCounts has executed. Set this to false to force re-execution of Changed_FeatureCount_ZeroFeatureValueInstanceCounts</summary>
		public bool Changed_FeatureCount_ZeroFeatureValueInstanceCounts_isDone;
		/// <summary>True if Changed_FeatureValues_InstanceCount_InstanceFeatureCounts has executed. Set this to false to force re-execution of Changed_FeatureValues_InstanceCount_InstanceFeatureCounts</summary>
		public bool Changed_FeatureValues_InstanceCount_InstanceFeatureCounts_isDone;
		/// <summary>True if Changed_InstanceCount_InstanceFeatureCounts has executed. Set this to false to force re-execution of Changed_InstanceCount_InstanceFeatureCounts</summary>
		public bool Changed_InstanceCount_InstanceFeatureCounts_isDone;
		/// <summary>True if Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10 has executed. Set this to false to force re-execution of Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10</summary>
		public bool Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isDone;
		/// <summary>True if Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10 has performed initialisation. Set this to false to force re-execution of Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10</summary>
		public bool Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised;
		/// <summary>True if Changed_InstanceCount has executed. Set this to false to force re-execution of Changed_InstanceCount</summary>
		public bool Changed_InstanceCount_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8</summary>
		public bool Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8</summary>
		public bool Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised;
		public Gamma CommonWeightPrecision_F;
		public Gamma[] CommonWeightPrecision_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal&lt;Gamma&gt;</summary>
		public Gamma CommonWeightPrecision_rep_B_toDef;
		public Gamma[] CommonWeightPrecision_rep_F;
		/// <summary>Buffer for ReplicateOp_Divide.UsesAverageConditional&lt;Gamma&gt;</summary>
		public Gamma CommonWeightPrecision_rep_F_marginal;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the FeatureCount property</summary>
		private int FeatureCount_field;
		/// <summary>Field backing the FeatureIndexes property</summary>
		private int[][] FeatureIndexes_field;
		public DistributionStructArray<Gaussian,double>[] FeatureScores_B;
		public DistributionStructArray<Gaussian,double>[] FeatureScores_F;
		/// <summary>Field backing the FeatureValues property</summary>
		private double[][] FeatureValues_field;
		public DistributionRefArray<DistributionStructArray<Gamma,double>,double[]> IndexedWeightPrecisionRates_B;
		public DistributionStructArray<Gaussian,double>[] IndexedWeights_B;
		/// <summary>Field backing the InstanceCount property</summary>
		private int InstanceCount_field;
		/// <summary>Field backing the InstanceFeatureCounts property</summary>
		private int[] InstanceFeatureCounts_field;
		/// <summary>Field backing the Labels property</summary>
		private bool[] Labels_field;
		/// <summary>Message to marginal of 'ModelSelector'</summary>
		public Bernoulli ModelSelector_marginal_F;
		public Bernoulli ModelSelector_selector_B;
		public Bernoulli ModelSelector_selector_cases_0_B;
		public Bernoulli[] ModelSelector_selector_cases_0_rep10_B;
		public Bernoulli[] ModelSelector_selector_cases_0_rep10_rpt_B;
		/// <summary>Messages from uses of 'ModelSelector_selector_cases_0_rep10'</summary>
		public Bernoulli[][] ModelSelector_selector_cases_0_rep10_uses_B;
		public Bernoulli[] ModelSelector_selector_cases_0_rep11_B;
		public Bernoulli ModelSelector_selector_cases_0_rep11_rpt_B_reduced;
		public Bernoulli[] ModelSelector_selector_cases_0_rep20_B;
		public Bernoulli[] ModelSelector_selector_cases_0_rep3_B;
		/// <summary>Messages from uses of 'ModelSelector_selector_cases_0_rep3'</summary>
		public Bernoulli[][] ModelSelector_selector_cases_0_rep3_uses_B;
		public Bernoulli[] ModelSelector_selector_cases_0_rep4_B;
		public Bernoulli[] ModelSelector_selector_cases_0_rep5_B;
		public Bernoulli[] ModelSelector_selector_cases_0_rep6_B;
		/// <summary>Messages from uses of 'ModelSelector_selector_cases_0_rep6'</summary>
		public Bernoulli[][] ModelSelector_selector_cases_0_rep6_uses_B;
		public Bernoulli[] ModelSelector_selector_cases_0_rep8_B;
		public Bernoulli[][] ModelSelector_selector_cases_0_rep8_rep_B;
		/// <summary>Messages from uses of 'ModelSelector_selector_cases_0'</summary>
		public Bernoulli[] ModelSelector_selector_cases_0_uses_B;
		public DistributionStructArray<Bernoulli,bool> ModelSelector_selector_cases_B;
		public Gaussian[] NoisyScore_F;
		/// <summary>Message from use of 'NoisyScore'</summary>
		public Gaussian[] NoisyScore_use_B;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		public Gaussian[] Score_B;
		public Gaussian[] Score_F;
		/// <summary>Buffer for GammaFromShapeAndRateOp_Laplace.LogEvidenceRatio</summary>
		public Gamma[] SharedWeightPrecisionRates_B_FeatureRange__Q;
		public DistributionStructArray<Gamma,double> SharedWeightPrecisionRates_F;
		/// <summary>Message from use of 'SharedWeightPrecisionRates'</summary>
		public DistributionStructArray<Gamma,double> SharedWeightPrecisionRates_use_B;
		/// <summary>Messages from uses of 'SharedWeightPrecisionRates_use'</summary>
		public Gamma[][] SharedWeightPrecisionRates_uses_B;
		/// <summary>Messages to uses of 'SharedWeightPrecisionRates_use'</summary>
		public Gamma[][] SharedWeightPrecisionRates_uses_F;
		/// <summary>The constant 'vBernoulli5'</summary>
		public Bernoulli vBernoulli5;
		/// <summary>Field backing the WeightConstraints property</summary>
		private DistributionStructArray<Gaussian,double> WeightConstraints_field;
		/// <summary>Field backing the WeightPrecisionRateConstraints property</summary>
		private DistributionStructArray<Gamma,double> WeightPrecisionRateConstraints_field;
		public Gamma WeightPrecisionRateRates_F_reduced;
		public DistributionStructArray<Gamma,double> WeightPrecisionRates_depth0_B;
		public DistributionStructArray<Gamma,double> WeightPrecisionRates_depth0_F;
		/// <summary>Message to marginal of 'WeightPrecisionRates_depth0'</summary>
		public DistributionStructArray<Gamma,double> WeightPrecisionRates_depth0_marginal_F;
		/// <summary>Messages from uses of 'WeightPrecisionRates_depth0'</summary>
		public DistributionStructArray<Gamma,double>[] WeightPrecisionRates_depth0_uses_B;
		/// <summary>Messages to uses of 'WeightPrecisionRates_depth0'</summary>
		public DistributionStructArray<Gamma,double>[] WeightPrecisionRates_depth0_uses_F;
		public DistributionRefArray<DistributionStructArray<Gamma,double>,double[]> WeightPrecisionRates_FeatureIndexes_F;
		/// <summary>Message to marginal of 'WeightPrecisionRates'</summary>
		public DistributionStructArray<Gamma,double> WeightPrecisionRates_marginal_F;
		public Gamma WeightPrecisionRates_rpt_B_reduced;
		public Gamma[] WeightPrecisionRates_rpt_F;
		/// <summary>Message from use of 'WeightPrecisionRates'</summary>
		public DistributionStructArray<Gamma,double> WeightPrecisionRates_use_B;
		/// <summary>Messages from uses of 'WeightPrecisionRates_use'</summary>
		public Gamma[][] WeightPrecisionRates_uses_B;
		/// <summary>Messages to uses of 'WeightPrecisionRates_use'</summary>
		public Gamma[][] WeightPrecisionRates_uses_F;
		public DistributionStructArray<Gamma,double> WeightPrecisions_B;
		/// <summary>Buffer for GammaRatioOp_Laplace.LogEvidenceRatio</summary>
		public Gamma[] WeightPrecisions_B_FeatureRange__Q;
		public DistributionStructArray<Gamma,double> WeightPrecisions_F;
		public DistributionStructArray<Gaussian,double> Weights_B;
		public DistributionStructArray<Gaussian,double> Weights_F;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Weights_FeatureIndexes_F;
		/// <summary>Message to marginal of 'Weights'</summary>
		public DistributionStructArray<Gaussian,double> Weights_marginal_F;
		/// <summary>Messages from uses of 'Weights'</summary>
		public DistributionStructArray<Gaussian,double>[] Weights_uses_B;
		/// <summary>Messages to uses of 'Weights'</summary>
		public DistributionStructArray<Gaussian,double>[] Weights_uses_F;
		public double Zero_reduced;
		/// <summary>Field backing the ZeroFeatureValueInstanceCounts property</summary>
		private double[] ZeroFeatureValueInstanceCounts_field;
		#endregion

		#region Properties
		/// <summary>The externally-specified value of 'FeatureCount'</summary>
		public int FeatureCount
		{
			get {
				return this.FeatureCount_field;
			}
			set {
				if (this.FeatureCount_field!=value) {
					this.FeatureCount_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
					this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised = false;
					this.Changed_FeatureCount_isDone = false;
					this.Changed_FeatureCount_WeightConstraints_isDone = false;
					this.Changed_FeatureCount_WeightPrecisionRateConstraints_isDone = false;
					this.Changed_FeatureCount_ZeroFeatureValueInstanceCounts_isDone = false;
					this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isDone = false;
					this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isDone = false;
					this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
				}
			}
		}

		/// <summary>The externally-specified value of 'FeatureIndexes'</summary>
		public int[][] FeatureIndexes
		{
			get {
				return this.FeatureIndexes_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.InstanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.InstanceCount)+" was expected for variable \'FeatureIndexes\'");
				}
				this.FeatureIndexes_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
				this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised = false;
				this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isDone = false;
				this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'FeatureValues'</summary>
		public double[][] FeatureValues
		{
			get {
				return this.FeatureValues_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.InstanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.InstanceCount)+" was expected for variable \'FeatureValues\'");
				}
				this.FeatureValues_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
				this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised = false;
				this.Changed_FeatureValues_InstanceCount_InstanceFeatureCounts_isDone = false;
				this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'InstanceCount'</summary>
		public int InstanceCount
		{
			get {
				return this.InstanceCount_field;
			}
			set {
				if (this.InstanceCount_field!=value) {
					this.InstanceCount_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
					this.Changed_InstanceCount_isDone = false;
					this.Changed_InstanceCount_InstanceFeatureCounts_isDone = false;
					this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isDone = false;
					this.Changed_FeatureValues_InstanceCount_InstanceFeatureCounts_isDone = false;
					this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = false;
					this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isDone = false;
					this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
				}
			}
		}

		/// <summary>The externally-specified value of 'InstanceFeatureCounts'</summary>
		public int[] InstanceFeatureCounts
		{
			get {
				return this.InstanceFeatureCounts_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.InstanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.InstanceCount)+" was expected for variable \'InstanceFeatureCounts\'");
				}
				this.InstanceFeatureCounts_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
				this.Changed_InstanceCount_InstanceFeatureCounts_isDone = false;
				this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isDone = false;
				this.Changed_FeatureValues_InstanceCount_InstanceFeatureCounts_isDone = false;
				this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isDone = false;
				this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'Labels'</summary>
		public bool[] Labels
		{
			get {
				return this.Labels_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.InstanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.InstanceCount)+" was expected for variable \'Labels\'");
				}
				this.Labels_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
				this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised = false;
				this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
			}
		}

		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'WeightConstraints'</summary>
		public DistributionStructArray<Gaussian,double> WeightConstraints
		{
			get {
				return this.WeightConstraints_field;
			}
			set {
				this.WeightConstraints_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
				this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised = false;
				this.Changed_FeatureCount_WeightConstraints_isDone = false;
				this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'WeightPrecisionRateConstraints'</summary>
		public DistributionStructArray<Gamma,double> WeightPrecisionRateConstraints
		{
			get {
				return this.WeightPrecisionRateConstraints_field;
			}
			set {
				this.WeightPrecisionRateConstraints_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
				this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised = false;
				this.Changed_FeatureCount_WeightPrecisionRateConstraints_isDone = false;
				this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'ZeroFeatureValueInstanceCounts'</summary>
		public double[] ZeroFeatureValueInstanceCounts
		{
			get {
				return this.ZeroFeatureValueInstanceCounts_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.FeatureCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.FeatureCount)+" was expected for variable \'ZeroFeatureValueInstanceCounts\'");
				}
				this.ZeroFeatureValueInstanceCounts_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = false;
				this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised = false;
				this.Changed_FeatureCount_ZeroFeatureValueInstanceCounts_isDone = false;
				this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isInitialised = false;
				this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of FeatureCount</summary>
		private void Changed_FeatureCount()
		{
			if (this.Changed_FeatureCount_isDone) {
				return ;
			}
			this.ModelSelector_selector_cases_0_rep3_uses_B = new Bernoulli[this.FeatureCount][];
			this.ModelSelector_selector_cases_0_rep3_B = new Bernoulli[this.FeatureCount];
			this.SharedWeightPrecisionRates_B_FeatureRange__Q = new Gamma[this.FeatureCount];
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.SharedWeightPrecisionRates_B_FeatureRange__Q[FeatureRange] = default(Gamma);
			}
			this.SharedWeightPrecisionRates_use_B = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			this.WeightPrecisionRateRates_F_reduced = default(Gamma);
			if (this.FeatureCount>0) {
				this.WeightPrecisionRateRates_F_reduced = GammaFromShapeAndRateOpBase.SampleAverageConditional(1.0, 1.0);
			}
			this.SharedWeightPrecisionRates_F = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.SharedWeightPrecisionRates_F[FeatureRange] = Gamma.Uniform();
			}
			this.SharedWeightPrecisionRates_uses_F = new Gamma[this.FeatureCount][];
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.SharedWeightPrecisionRates_uses_F[FeatureRange] = new Gamma[2];
				this.SharedWeightPrecisionRates_uses_F[FeatureRange][1] = Gamma.Uniform();
				this.SharedWeightPrecisionRates_uses_F[FeatureRange][0] = Gamma.Uniform();
			}
			this.SharedWeightPrecisionRates_uses_B = new Gamma[this.FeatureCount][];
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.SharedWeightPrecisionRates_uses_B[FeatureRange] = new Gamma[2];
				this.SharedWeightPrecisionRates_uses_B[FeatureRange][1] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_uses_F = new Gamma[this.FeatureCount][];
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_uses_F[FeatureRange] = new Gamma[2];
				this.WeightPrecisionRates_uses_F[FeatureRange][0] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_uses_B = new Gamma[this.FeatureCount][];
			this.WeightPrecisionRates_rpt_B_reduced = default(Gamma);
			if (this.FeatureCount>0) {
				this.WeightPrecisionRates_rpt_B_reduced = GaussianOpBase.PrecisionAverageConditional(0.0, 0.0);
			}
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_uses_B[FeatureRange] = new Gamma[2];
				this.WeightPrecisionRates_uses_B[FeatureRange][1] = Gamma.Uniform();
				this.WeightPrecisionRates_uses_B[FeatureRange][0] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_depth0_F = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_depth0_F[FeatureRange] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_depth0_uses_F[1] = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_depth0_uses_F[1][FeatureRange] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_depth0_uses_B[0] = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_depth0_uses_B[0][FeatureRange] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_depth0_marginal_F = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_depth0_marginal_F[FeatureRange] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_depth0_uses_B[1] = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_depth0_uses_B[1][FeatureRange] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_depth0_B = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_depth0_B[FeatureRange] = Gamma.Uniform();
			}
			this.WeightPrecisionRates_use_B = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_use_B[FeatureRange] = Gamma.Uniform();
			}
			this.WeightPrecisions_B_FeatureRange__Q = new Gamma[this.FeatureCount];
			this.CommonWeightPrecision_rep_F = new Gamma[this.FeatureCount];
			this.CommonWeightPrecision_rep_B = new Gamma[this.FeatureCount];
			this.WeightPrecisions_B = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			this.WeightPrecisions_F = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisions_F[FeatureRange] = Gamma.Uniform();
			}
			this.Weights_F = new DistributionStructArray<Gaussian,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.Weights_F[FeatureRange] = Gaussian.Uniform();
			}
			this.Weights_B = new DistributionStructArray<Gaussian,double>(this.FeatureCount);
			this.Weights_uses_F[1] = new DistributionStructArray<Gaussian,double>(this.FeatureCount);
			this.Weights_uses_B[0] = new DistributionStructArray<Gaussian,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.Weights_uses_B[0][FeatureRange] = Gaussian.Uniform();
			}
			this.Weights_marginal_F = new DistributionStructArray<Gaussian,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.Weights_marginal_F[FeatureRange] = Gaussian.Uniform();
			}
			this.Weights_uses_B[1] = new DistributionStructArray<Gaussian,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.ModelSelector_selector_cases_0_rep3_uses_B[FeatureRange] = new Bernoulli[3];
				this.ModelSelector_selector_cases_0_rep3_uses_B[FeatureRange][1] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep3_uses_B[FeatureRange][0] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep3_uses_B[FeatureRange][2] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep3_B[FeatureRange] = Bernoulli.Uniform();
			}
			this.ModelSelector_selector_cases_0_rep4_B = new Bernoulli[this.FeatureCount];
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.ModelSelector_selector_cases_0_rep4_B[FeatureRange] = Bernoulli.Uniform();
			}
			this.ModelSelector_selector_cases_0_rep5_B = new Bernoulli[this.FeatureCount];
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.ModelSelector_selector_cases_0_rep5_B[FeatureRange] = Bernoulli.Uniform();
			}
			this.Weights_uses_F[0] = new DistributionStructArray<Gaussian,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.Weights_uses_F[0][FeatureRange] = Gaussian.Uniform();
			}
			this.ModelSelector_selector_cases_0_rep6_uses_B = new Bernoulli[this.FeatureCount][];
			this.ModelSelector_selector_cases_0_rep10_rpt_B = new Bernoulli[this.FeatureCount];
			this.WeightPrecisionRates_rpt_F = new Gamma[this.FeatureCount];
			this.ModelSelector_selector_cases_0_rep10_B = new Bernoulli[this.FeatureCount];
			this.ModelSelector_selector_cases_0_rep10_uses_B = new Bernoulli[this.FeatureCount][];
			this.ModelSelector_selector_cases_0_rep6_B = new Bernoulli[this.FeatureCount];
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.ModelSelector_selector_cases_0_rep6_uses_B[FeatureRange] = new Bernoulli[3];
				this.ModelSelector_selector_cases_0_rep6_uses_B[FeatureRange][1] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep6_uses_B[FeatureRange][0] = Bernoulli.Uniform();
				this.WeightPrecisionRates_uses_F[FeatureRange][1] = Gamma.Uniform();
				this.ModelSelector_selector_cases_0_rep6_uses_B[FeatureRange][2] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep6_B[FeatureRange] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep10_uses_B[FeatureRange] = new Bernoulli[3];
				this.ModelSelector_selector_cases_0_rep10_uses_B[FeatureRange][1] = Bernoulli.Uniform();
				this.WeightPrecisionRates_rpt_F[FeatureRange] = Gamma.Uniform();
				this.ModelSelector_selector_cases_0_rep10_rpt_B[FeatureRange] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep10_uses_B[FeatureRange][0] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep10_uses_B[FeatureRange][2] = Bernoulli.Uniform();
				this.ModelSelector_selector_cases_0_rep10_B[FeatureRange] = Bernoulli.Uniform();
			}
			this.WeightPrecisionRates_depth0_uses_F[0] = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_depth0_uses_F[0][FeatureRange] = Gamma.Uniform();
			}
			this.Zero_reduced = default(double);
			if (this.FeatureCount>0) {
				this.Zero_reduced = 0.0;
			}
			this.ModelSelector_selector_cases_0_rep11_rpt_B_reduced = default(Bernoulli);
			if (this.FeatureCount>0) {
				this.ModelSelector_selector_cases_0_rep11_rpt_B_reduced = Bernoulli.FromLogOdds(ConstrainEqualOp<double>.LogEvidenceRatio(this.Zero_reduced, 0.0));
			}
			this.ModelSelector_selector_cases_0_rep11_B = new Bernoulli[this.FeatureCount];
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.ModelSelector_selector_cases_0_rep11_B[FeatureRange] = Bernoulli.Uniform();
			}
			this.WeightPrecisionRates_marginal_F = new DistributionStructArray<Gamma,double>(this.FeatureCount);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_marginal_F[FeatureRange] = Gamma.Uniform();
			}
			this.Changed_FeatureCount_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of FeatureCount and FeatureIndexes and FeatureValues and InstanceCount and InstanceFeatureCounts and Labels and numberOfIterations and WeightConstraints and WeightPrecisionRateConstraints and ZeroFeatureValueInstanceCounts</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12(int numberOfIterations)
		{
			if (this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone) {
				return ;
			}
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
					this.SharedWeightPrecisionRates_B_FeatureRange__Q[FeatureRange] = GammaFromShapeAndRateOp_Laplace.Q(this.SharedWeightPrecisionRates_use_B[FeatureRange], 1.0, this.WeightPrecisionRateRates_F_reduced);
					this.SharedWeightPrecisionRates_F[FeatureRange] = GammaFromShapeAndRateOp_Laplace.SampleAverageConditional(this.SharedWeightPrecisionRates_use_B[FeatureRange], 1.0, this.WeightPrecisionRateRates_F_reduced, this.SharedWeightPrecisionRates_B_FeatureRange__Q[FeatureRange]);
					this.SharedWeightPrecisionRates_uses_F[FeatureRange][1] = ReplicateOp_NoDivide.UsesAverageConditional<Gamma>(this.SharedWeightPrecisionRates_uses_B[FeatureRange], this.SharedWeightPrecisionRates_F[FeatureRange], 1, this.SharedWeightPrecisionRates_uses_F[FeatureRange][1]);
					this.WeightPrecisionRates_uses_F[FeatureRange][0] = ReplicateOp_NoDivide.UsesAverageConditional<Gamma>(this.WeightPrecisionRates_uses_B[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][1], 0, this.WeightPrecisionRates_uses_F[FeatureRange][0]);
					this.WeightPrecisionRates_depth0_F[FeatureRange] = ArrayHelper.SetTo<Gamma>(this.WeightPrecisionRates_depth0_F[FeatureRange], this.WeightPrecisionRates_uses_F[FeatureRange][0]);
				}
				this.WeightPrecisionRates_depth0_uses_F[1] = ReplicateOp_NoDivide.UsesAverageConditional<DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_B, this.WeightPrecisionRates_depth0_F, 1, this.WeightPrecisionRates_depth0_uses_F[1]);
				this.WeightPrecisionRates_depth0_marginal_F = JaggedSubarrayWithMarginalOp<double>.MarginalAverageConditional<DistributionStructArray<Gamma,double>,Gamma,DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_F[1], this.IndexedWeightPrecisionRates_B, this.FeatureIndexes, this.WeightPrecisionRates_depth0_marginal_F);
				this.WeightPrecisionRates_depth0_uses_B[1] = JaggedSubarrayWithMarginalOp<double>.ArrayAverageConditional<DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_F[1], this.WeightPrecisionRates_depth0_marginal_F, this.WeightPrecisionRates_depth0_uses_B[1]);
				this.WeightPrecisionRates_depth0_B = ReplicateOp_NoDivide.DefAverageConditional<DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_B, this.WeightPrecisionRates_depth0_B);
				for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
					this.WeightPrecisionRates_uses_B[FeatureRange][0] = ArrayHelper.SetTo<Gamma>(this.WeightPrecisionRates_uses_B[FeatureRange][0], this.WeightPrecisionRates_depth0_B[FeatureRange]);
					this.WeightPrecisionRates_use_B[FeatureRange] = ReplicateOp_NoDivide.DefAverageConditional<Gamma>(this.WeightPrecisionRates_uses_B[FeatureRange], this.WeightPrecisionRates_use_B[FeatureRange]);
					this.SharedWeightPrecisionRates_uses_B[FeatureRange][1] = ArrayHelper.SetTo<Gamma>(this.SharedWeightPrecisionRates_uses_B[FeatureRange][1], this.WeightPrecisionRates_use_B[FeatureRange]);
					this.SharedWeightPrecisionRates_uses_F[FeatureRange][0] = ReplicateOp_NoDivide.UsesAverageConditional<Gamma>(this.SharedWeightPrecisionRates_uses_B[FeatureRange], this.SharedWeightPrecisionRates_F[FeatureRange], 0, this.SharedWeightPrecisionRates_uses_F[FeatureRange][0]);
					this.WeightPrecisions_B_FeatureRange__Q[FeatureRange] = GammaRatioOp_Laplace.Q(this.WeightPrecisions_B[FeatureRange], this.CommonWeightPrecision_rep_F[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][0]);
					this.CommonWeightPrecision_rep_B[FeatureRange] = GammaRatioOp_Laplace.AAverageConditional(this.WeightPrecisions_B[FeatureRange], this.CommonWeightPrecision_rep_F[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][0], this.WeightPrecisions_B_FeatureRange__Q[FeatureRange]);
				}
				this.CommonWeightPrecision_rep_B_toDef = ReplicateOp_Divide.ToDef<Gamma>(this.CommonWeightPrecision_rep_B, this.CommonWeightPrecision_rep_B_toDef);
				this.CommonWeightPrecision_rep_F_marginal = ReplicateOp_Divide.Marginal<Gamma>(this.CommonWeightPrecision_rep_B_toDef, this.CommonWeightPrecision_F, this.CommonWeightPrecision_rep_F_marginal);
				for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
					this.CommonWeightPrecision_rep_F[FeatureRange] = ReplicateOp_Divide.UsesAverageConditional<Gamma>(this.CommonWeightPrecision_rep_B[FeatureRange], this.CommonWeightPrecision_rep_F_marginal, FeatureRange, this.CommonWeightPrecision_rep_F[FeatureRange]);
					this.WeightPrecisions_F[FeatureRange] = GammaRatioOp_Laplace.RatioAverageConditional(this.WeightPrecisions_B[FeatureRange], this.CommonWeightPrecision_rep_F[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][0]);
					this.Weights_F[FeatureRange] = GaussianOp.SampleAverageConditional(this.Weights_B[FeatureRange], 0.0, this.WeightPrecisions_F[FeatureRange], this.WeightPrecisions_B[FeatureRange]);
				}
				this.Weights_uses_F[1] = ReplicateOp_NoDivide.UsesAverageConditional<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B, this.Weights_F, 1, this.Weights_uses_F[1]);
				this.Weights_marginal_F = JaggedSubarrayWithMarginalOp<double>.MarginalIncrementArray<DistributionStructArray<Gaussian,double>>(this.Weights_uses_F[1], this.Weights_uses_B[1], this.Weights_marginal_F);
				for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
					this.Weights_FeatureIndexes_F[InstanceRange] = JaggedSubarrayWithMarginalOp<double>.ItemsAverageConditional<DistributionStructArray<Gaussian,double>,Gaussian,DistributionStructArray<Gaussian,double>>(this.IndexedWeights_B[InstanceRange], this.Weights_uses_F[1], this.Weights_marginal_F, this.FeatureIndexes, InstanceRange, this.Weights_FeatureIndexes_F[InstanceRange]);
					for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
						this.FeatureScores_F[InstanceRange][InstanceFeatureRanges] = GaussianProductOpBase.ProductAverageConditional(this.FeatureValues[InstanceRange][InstanceFeatureRanges], this.Weights_FeatureIndexes_F[InstanceRange][InstanceFeatureRanges]);
					}
					this.Score_F[InstanceRange] = FastSumOp.SumAverageConditional(this.FeatureScores_F[InstanceRange]);
					this.NoisyScore_F[InstanceRange] = GaussianFromMeanAndVarianceOp.SampleAverageConditional(this.Score_F[InstanceRange], 1.0);
					this.NoisyScore_use_B[InstanceRange] = IsPositiveOp_Proper.XAverageConditional(Bernoulli.PointMass(this.Labels[InstanceRange]), this.NoisyScore_F[InstanceRange]);
					this.Score_B[InstanceRange] = GaussianFromMeanAndVarianceOp.MeanAverageConditional(this.NoisyScore_use_B[InstanceRange], 1.0);
					this.FeatureScores_B[InstanceRange] = FastSumOp.ArrayAverageConditional<DistributionStructArray<Gaussian,double>>(this.Score_B[InstanceRange], this.Score_F[InstanceRange], this.FeatureScores_F[InstanceRange], this.FeatureScores_B[InstanceRange]);
					for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
						this.IndexedWeights_B[InstanceRange][InstanceFeatureRanges] = GaussianProductOpBase.BAverageConditional(this.FeatureScores_B[InstanceRange][InstanceFeatureRanges], this.FeatureValues[InstanceRange][InstanceFeatureRanges]);
					}
					this.Weights_marginal_F = JaggedSubarrayWithMarginalOp<double>.MarginalIncrementItems<DistributionStructArray<Gaussian,double>,Gaussian,DistributionStructArray<Gaussian,double>>(this.IndexedWeights_B[InstanceRange], this.Weights_FeatureIndexes_F[InstanceRange], this.FeatureIndexes, InstanceRange, this.Weights_marginal_F);
				}
				this.Weights_uses_B[1] = JaggedSubarrayWithMarginalOp<double>.ArrayAverageConditional<DistributionStructArray<Gaussian,double>>(this.Weights_uses_F[1], this.Weights_marginal_F, this.Weights_uses_B[1]);
				this.Weights_B = ReplicateOp_NoDivide.DefAverageConditional<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B, this.Weights_B);
				for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
					this.WeightPrecisions_B[FeatureRange] = GaussianOp.PrecisionAverageConditional(this.Weights_B[FeatureRange], Gaussian.PointMass(0.0), this.WeightPrecisions_F[FeatureRange]);
					this.WeightPrecisions_B_FeatureRange__Q[FeatureRange] = GammaRatioOp_Laplace.Q(this.WeightPrecisions_B[FeatureRange], this.CommonWeightPrecision_rep_F[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][0]);
					this.SharedWeightPrecisionRates_uses_B[FeatureRange][0] = GammaRatioOp_Laplace.BAverageConditional(this.WeightPrecisions_B[FeatureRange], this.CommonWeightPrecision_rep_F[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][0], this.WeightPrecisions_B_FeatureRange__Q[FeatureRange]);
					this.SharedWeightPrecisionRates_use_B[FeatureRange] = ReplicateOp_NoDivide.DefAverageConditional<Gamma>(this.SharedWeightPrecisionRates_uses_B[FeatureRange], this.SharedWeightPrecisionRates_use_B[FeatureRange]);
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			this.WeightPrecisionRates_depth0_marginal_F = JaggedSubarrayWithMarginalOp<double>.MarginalIncrementArray<DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_F[1], this.WeightPrecisionRates_depth0_uses_B[1], this.WeightPrecisionRates_depth0_marginal_F);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.ModelSelector_selector_cases_0_rep3_uses_B[FeatureRange][0] = Bernoulli.FromLogOdds(GammaFromShapeAndRateOp_Laplace.LogEvidenceRatio(this.SharedWeightPrecisionRates_use_B[FeatureRange], 1.0, this.WeightPrecisionRateRates_F_reduced, this.SharedWeightPrecisionRates_F[FeatureRange], this.SharedWeightPrecisionRates_B_FeatureRange__Q[FeatureRange]));
				this.ModelSelector_selector_cases_0_rep3_uses_B[FeatureRange][2] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Gamma>(this.SharedWeightPrecisionRates_uses_B[FeatureRange], this.SharedWeightPrecisionRates_F[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange]));
				this.ModelSelector_selector_cases_0_rep3_B[FeatureRange] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep3_uses_B[FeatureRange], this.ModelSelector_selector_cases_0_rep3_B[FeatureRange]);
			}
			this.ModelSelector_selector_cases_0_uses_B[15] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep3_B, this.ModelSelector_selector_cases_0_uses_B[15]);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.ModelSelector_selector_cases_0_rep4_B[FeatureRange] = Bernoulli.FromLogOdds(GammaRatioOp_Laplace.LogEvidenceRatio(this.WeightPrecisions_B[FeatureRange], this.CommonWeightPrecision_rep_F[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][0], this.WeightPrecisions_F[FeatureRange], this.WeightPrecisions_B_FeatureRange__Q[FeatureRange]));
			}
			this.ModelSelector_selector_cases_0_uses_B[19] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep4_B, this.ModelSelector_selector_cases_0_uses_B[19]);
			this.ModelSelector_selector_cases_0_uses_B[21] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Gamma>(this.CommonWeightPrecision_rep_B, this.CommonWeightPrecision_F, this.CommonWeightPrecision_rep_F));
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.ModelSelector_selector_cases_0_rep5_B[FeatureRange] = Bernoulli.FromLogOdds(GaussianOp.LogEvidenceRatio(this.Weights_B[FeatureRange], 0.0, this.WeightPrecisions_F[FeatureRange], this.Weights_F[FeatureRange], this.WeightPrecisions_B[FeatureRange]));
			}
			this.ModelSelector_selector_cases_0_uses_B[22] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep5_B, this.ModelSelector_selector_cases_0_uses_B[22]);
			this.Weights_uses_F[0] = ReplicateOp_NoDivide.UsesAverageConditional<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B, this.Weights_F, 0, this.Weights_uses_F[0]);
			this.ModelSelector_selector_cases_0_uses_B[24] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B, this.Weights_F, this.Weights_uses_F));
			this.ModelSelector_selector_cases_0_uses_B[25] = Bernoulli.FromLogOdds(ConstrainEqualRandomOp<double[]>.LogEvidenceRatio<DistributionStructArray<Gaussian,double>>(this.Weights_uses_F[0], this.WeightConstraints));
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_uses_F[FeatureRange][1] = ReplicateOp_NoDivide.UsesAverageConditional<Gamma>(this.WeightPrecisionRates_uses_B[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][1], 1, this.WeightPrecisionRates_uses_F[FeatureRange][1]);
				this.ModelSelector_selector_cases_0_rep6_uses_B[FeatureRange][2] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Gamma>(this.WeightPrecisionRates_uses_B[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][1], this.WeightPrecisionRates_uses_F[FeatureRange]));
				this.ModelSelector_selector_cases_0_rep6_B[FeatureRange] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep6_uses_B[FeatureRange], this.ModelSelector_selector_cases_0_rep6_B[FeatureRange]);
				this.WeightPrecisionRates_rpt_F[FeatureRange] = PowerPlateOp.EnterAverageConditional<Gamma>(this.WeightPrecisionRates_rpt_B_reduced, this.WeightPrecisionRates_uses_F[FeatureRange][1], this.ZeroFeatureValueInstanceCounts[FeatureRange], this.WeightPrecisionRates_rpt_F[FeatureRange]);
				this.ModelSelector_selector_cases_0_rep10_rpt_B[FeatureRange] = Bernoulli.FromLogOdds(GaussianOpBase.LogEvidenceRatio(0.0, 0.0, this.WeightPrecisionRates_rpt_F[FeatureRange]));
				this.ModelSelector_selector_cases_0_rep10_uses_B[FeatureRange][0] = PowerPlateOp.ValueAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep10_rpt_B[FeatureRange], this.ZeroFeatureValueInstanceCounts[FeatureRange], this.ModelSelector_selector_cases_0_rep10_uses_B[FeatureRange][0]);
				this.ModelSelector_selector_cases_0_rep10_uses_B[FeatureRange][2] = Bernoulli.FromLogOdds(PowerPlateOp.LogEvidenceRatio<Gamma>(this.WeightPrecisionRates_rpt_B_reduced, this.WeightPrecisionRates_uses_F[FeatureRange][1], this.ZeroFeatureValueInstanceCounts[FeatureRange], this.WeightPrecisionRates_rpt_F[FeatureRange]));
				this.ModelSelector_selector_cases_0_rep10_B[FeatureRange] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep10_uses_B[FeatureRange], this.ModelSelector_selector_cases_0_rep10_B[FeatureRange]);
			}
			this.ModelSelector_selector_cases_0_uses_B[26] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep6_B, this.ModelSelector_selector_cases_0_uses_B[26]);
			this.WeightPrecisionRates_depth0_uses_F[0] = ReplicateOp_NoDivide.UsesAverageConditional<DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_B, this.WeightPrecisionRates_depth0_F, 0, this.WeightPrecisionRates_depth0_uses_F[0]);
			this.ModelSelector_selector_cases_0_uses_B[33] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_B, this.WeightPrecisionRates_depth0_F, this.WeightPrecisionRates_depth0_uses_F));
			this.ModelSelector_selector_cases_0_uses_B[34] = Bernoulli.FromLogOdds(ConstrainEqualRandomOp<double[]>.LogEvidenceRatio<DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_F[0], this.WeightPrecisionRateConstraints));
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.WeightPrecisionRates_FeatureIndexes_F[InstanceRange] = JaggedSubarrayWithMarginalOp<double>.ItemsAverageConditional<DistributionStructArray<Gamma,double>,Gamma,DistributionStructArray<Gamma,double>>(this.IndexedWeightPrecisionRates_B[InstanceRange], this.WeightPrecisionRates_depth0_uses_F[1], this.WeightPrecisionRates_depth0_marginal_F, this.FeatureIndexes, InstanceRange, this.WeightPrecisionRates_FeatureIndexes_F[InstanceRange]);
			}
			this.ModelSelector_selector_cases_0_uses_B[37] = Bernoulli.FromLogOdds(JaggedSubarrayWithMarginalOp<double>.LogEvidenceRatio<Gamma>(this.IndexedWeightPrecisionRates_B, this.WeightPrecisionRates_depth0_uses_F[1], this.FeatureIndexes, this.WeightPrecisionRates_FeatureIndexes_F));
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.ModelSelector_selector_cases_0_rep8_rep_B[InstanceRange][InstanceFeatureRanges] = Bernoulli.FromLogOdds(GaussianOpBase.LogEvidenceRatio(this.FeatureValues[InstanceRange][InstanceFeatureRanges], 0.0, this.WeightPrecisionRates_FeatureIndexes_F[InstanceRange][InstanceFeatureRanges]));
				}
				this.ModelSelector_selector_cases_0_rep8_B[InstanceRange] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep8_rep_B[InstanceRange], this.ModelSelector_selector_cases_0_rep8_B[InstanceRange]);
			}
			this.ModelSelector_selector_cases_0_uses_B[39] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep8_B, this.ModelSelector_selector_cases_0_uses_B[39]);
			this.ModelSelector_selector_cases_0_uses_B[41] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep10_B, this.ModelSelector_selector_cases_0_uses_B[41]);
			this.ModelSelector_selector_cases_0_uses_B[46] = Bernoulli.FromLogOdds(JaggedSubarrayWithMarginalOp<double>.LogEvidenceRatio<Gaussian>(this.IndexedWeights_B, this.Weights_uses_F[1], this.FeatureIndexes, this.Weights_FeatureIndexes_F));
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.ModelSelector_selector_cases_0_rep20_B[InstanceRange] = Bernoulli.FromLogOdds(IsPositiveOp.LogEvidenceRatio(this.Labels[InstanceRange], this.NoisyScore_F[InstanceRange]));
			}
			this.ModelSelector_selector_cases_0_uses_B[54] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep20_B, this.ModelSelector_selector_cases_0_uses_B[54]);
			this.ModelSelector_selector_cases_0_B = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_uses_B, this.ModelSelector_selector_cases_0_B);
			this.ModelSelector_selector_cases_B[0] = ArrayHelper.SetTo<Bernoulli>(this.ModelSelector_selector_cases_B[0], this.ModelSelector_selector_cases_0_B);
			this.ModelSelector_selector_B = CasesOp.BAverageConditional(this.ModelSelector_selector_cases_B);
			this.ModelSelector_marginal_F = VariableOp.MarginalAverageConditional<Bernoulli>(this.ModelSelector_selector_B, this.vBernoulli5, this.ModelSelector_marginal_F);
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_marginal_F[FeatureRange] = DerivedVariableOp.MarginalAverageConditional<Gamma>(this.WeightPrecisionRates_use_B[FeatureRange], this.SharedWeightPrecisionRates_uses_F[FeatureRange][1], this.WeightPrecisionRates_marginal_F[FeatureRange]);
			}
			this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of FeatureCount and FeatureIndexes and InstanceCount and InstanceFeatureCounts and numberOfIterationsDecreased and must reset on changes to FeatureValues and Labels and WeightConstraints and WeightPrecisionRateConstraints and ZeroFeatureValueInstanceCounts</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11(bool initialise)
		{
			if (this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isDone&&((!initialise)||this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isInitialised)) {
				return ;
			}
			this.Weights_marginal_F = JaggedSubarrayWithMarginalOp<double>.MarginalAverageConditional<DistributionStructArray<Gaussian,double>,Gaussian,DistributionStructArray<Gaussian,double>>(this.Weights_uses_F[1], this.IndexedWeights_B, this.FeatureIndexes, this.Weights_marginal_F);
			this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isDone = true;
			this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of FeatureCount and numberOfIterationsDecreased and must reset on changes to FeatureIndexes and FeatureValues and InstanceCount and InstanceFeatureCounts and Labels and WeightConstraints and WeightPrecisionRateConstraints and ZeroFeatureValueInstanceCounts</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2(bool initialise)
		{
			if (this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isDone&&((!initialise)||this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised)) {
				return ;
			}
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.SharedWeightPrecisionRates_use_B[FeatureRange] = Gamma.Uniform();
				this.SharedWeightPrecisionRates_uses_B[FeatureRange][0] = Gamma.Uniform();
				this.WeightPrecisions_B_FeatureRange__Q[FeatureRange] = default(Gamma);
				this.CommonWeightPrecision_rep_F[FeatureRange] = Gamma.Uniform();
				this.CommonWeightPrecision_rep_B[FeatureRange] = Gamma.Uniform();
				this.CommonWeightPrecision_rep_F[FeatureRange] = ReplicateOp_Divide.UsesAverageConditional<Gamma>(this.CommonWeightPrecision_rep_B[FeatureRange], this.CommonWeightPrecision_rep_F_marginal, FeatureRange, this.CommonWeightPrecision_rep_F[FeatureRange]);
				this.WeightPrecisions_B[FeatureRange] = Gamma.Uniform();
				this.Weights_B[FeatureRange] = Gaussian.Uniform();
				this.Weights_uses_F[1][FeatureRange] = Gaussian.Uniform();
				this.Weights_uses_B[1][FeatureRange] = Gaussian.Uniform();
			}
			this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isDone = true;
			this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of FeatureCount and WeightConstraints</summary>
		private void Changed_FeatureCount_WeightConstraints()
		{
			if (this.Changed_FeatureCount_WeightConstraints_isDone) {
				return ;
			}
			this.Weights_uses_B[0] = ArrayHelper.SetTo<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B[0], this.WeightConstraints);
			this.Changed_FeatureCount_WeightConstraints_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of FeatureCount and WeightPrecisionRateConstraints</summary>
		private void Changed_FeatureCount_WeightPrecisionRateConstraints()
		{
			if (this.Changed_FeatureCount_WeightPrecisionRateConstraints_isDone) {
				return ;
			}
			this.WeightPrecisionRates_depth0_uses_B[0] = ArrayHelper.SetTo<DistributionStructArray<Gamma,double>>(this.WeightPrecisionRates_depth0_uses_B[0], this.WeightPrecisionRateConstraints);
			this.Changed_FeatureCount_WeightPrecisionRateConstraints_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of FeatureCount and ZeroFeatureValueInstanceCounts</summary>
		private void Changed_FeatureCount_ZeroFeatureValueInstanceCounts()
		{
			if (this.Changed_FeatureCount_ZeroFeatureValueInstanceCounts_isDone) {
				return ;
			}
			for(int FeatureRange = 0; FeatureRange<this.FeatureCount; FeatureRange++) {
				this.WeightPrecisionRates_uses_B[FeatureRange][1] = PowerPlateOp.ValueAverageConditional<Gamma>(this.WeightPrecisionRates_rpt_B_reduced, this.ZeroFeatureValueInstanceCounts[FeatureRange], this.WeightPrecisionRates_uses_B[FeatureRange][1]);
				this.ModelSelector_selector_cases_0_rep11_B[FeatureRange] = PowerPlateOp.ValueAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep11_rpt_B_reduced, this.ZeroFeatureValueInstanceCounts[FeatureRange], this.ModelSelector_selector_cases_0_rep11_B[FeatureRange]);
			}
			this.ModelSelector_selector_cases_0_uses_B[42] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.ModelSelector_selector_cases_0_rep11_B, this.ModelSelector_selector_cases_0_uses_B[42]);
			this.Changed_FeatureCount_ZeroFeatureValueInstanceCounts_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of FeatureValues and InstanceCount and InstanceFeatureCounts</summary>
		private void Changed_FeatureValues_InstanceCount_InstanceFeatureCounts()
		{
			if (this.Changed_FeatureValues_InstanceCount_InstanceFeatureCounts_isDone) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.IndexedWeightPrecisionRates_B[InstanceRange][InstanceFeatureRanges] = GaussianOpBase.PrecisionAverageConditional(this.FeatureValues[InstanceRange][InstanceFeatureRanges], 0.0);
				}
			}
			this.Changed_FeatureValues_InstanceCount_InstanceFeatureCounts_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount</summary>
		private void Changed_InstanceCount()
		{
			if (this.Changed_InstanceCount_isDone) {
				return ;
			}
			this.IndexedWeightPrecisionRates_B = new DistributionRefArray<DistributionStructArray<Gamma,double>,double[]>(this.InstanceCount);
			this.IndexedWeights_B = new DistributionStructArray<Gaussian,double>[this.InstanceCount];
			this.Weights_FeatureIndexes_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.InstanceCount);
			this.FeatureScores_F = new DistributionStructArray<Gaussian,double>[this.InstanceCount];
			this.Score_F = new Gaussian[this.InstanceCount];
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.Score_F[InstanceRange] = Gaussian.Uniform();
			}
			this.NoisyScore_F = new Gaussian[this.InstanceCount];
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.NoisyScore_F[InstanceRange] = Gaussian.Uniform();
			}
			this.NoisyScore_use_B = new Gaussian[this.InstanceCount];
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.NoisyScore_use_B[InstanceRange] = Gaussian.Uniform();
			}
			this.Score_B = new Gaussian[this.InstanceCount];
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.Score_B[InstanceRange] = Gaussian.Uniform();
			}
			this.FeatureScores_B = new DistributionStructArray<Gaussian,double>[this.InstanceCount];
			this.WeightPrecisionRates_FeatureIndexes_F = new DistributionRefArray<DistributionStructArray<Gamma,double>,double[]>(this.InstanceCount);
			this.ModelSelector_selector_cases_0_rep8_rep_B = new Bernoulli[this.InstanceCount][];
			this.ModelSelector_selector_cases_0_rep8_B = new Bernoulli[this.InstanceCount];
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.ModelSelector_selector_cases_0_rep8_B[InstanceRange] = Bernoulli.Uniform();
			}
			this.ModelSelector_selector_cases_0_rep20_B = new Bernoulli[this.InstanceCount];
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.ModelSelector_selector_cases_0_rep20_B[InstanceRange] = Bernoulli.Uniform();
			}
			this.Changed_InstanceCount_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount and InstanceFeatureCounts</summary>
		private void Changed_InstanceCount_InstanceFeatureCounts()
		{
			if (this.Changed_InstanceCount_InstanceFeatureCounts_isDone) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				this.IndexedWeightPrecisionRates_B[InstanceRange] = new DistributionStructArray<Gamma,double>(this.InstanceFeatureCounts[InstanceRange]);
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.IndexedWeightPrecisionRates_B[InstanceRange][InstanceFeatureRanges] = Gamma.Uniform();
				}
				this.IndexedWeights_B[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.InstanceFeatureCounts[InstanceRange]);
				this.Weights_FeatureIndexes_F[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.InstanceFeatureCounts[InstanceRange]);
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.Weights_FeatureIndexes_F[InstanceRange][InstanceFeatureRanges] = Gaussian.Uniform();
				}
				this.FeatureScores_F[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.InstanceFeatureCounts[InstanceRange]);
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.FeatureScores_F[InstanceRange][InstanceFeatureRanges] = Gaussian.Uniform();
				}
				this.FeatureScores_B[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.InstanceFeatureCounts[InstanceRange]);
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.FeatureScores_B[InstanceRange][InstanceFeatureRanges] = Gaussian.Uniform();
				}
				this.WeightPrecisionRates_FeatureIndexes_F[InstanceRange] = new DistributionStructArray<Gamma,double>(this.InstanceFeatureCounts[InstanceRange]);
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.WeightPrecisionRates_FeatureIndexes_F[InstanceRange][InstanceFeatureRanges] = Gamma.Uniform();
				}
				this.ModelSelector_selector_cases_0_rep8_rep_B[InstanceRange] = new Bernoulli[this.InstanceFeatureCounts[InstanceRange]];
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.ModelSelector_selector_cases_0_rep8_rep_B[InstanceRange][InstanceFeatureRanges] = Bernoulli.Uniform();
				}
			}
			this.Changed_InstanceCount_InstanceFeatureCounts_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount and InstanceFeatureCounts and numberOfIterationsDecreased and must reset on changes to FeatureCount and FeatureIndexes and FeatureValues and Labels and WeightConstraints and WeightPrecisionRateConstraints and ZeroFeatureValueInstanceCounts</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10(bool initialise)
		{
			if (this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isDone&&((!initialise)||this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised)) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.InstanceCount; InstanceRange++) {
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.InstanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.IndexedWeights_B[InstanceRange][InstanceFeatureRanges] = Gaussian.Uniform();
				}
			}
			this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isDone = true;
			this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to FeatureCount and FeatureIndexes and FeatureValues and InstanceCount and InstanceFeatureCounts and Labels and WeightConstraints and WeightPrecisionRateConstraints and ZeroFeatureValueInstanceCounts</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised)) {
				return ;
			}
			this.CommonWeightPrecision_rep_F_marginal = ReplicateOp_Divide.MarginalInit<Gamma>(this.CommonWeightPrecision_F);
			this.CommonWeightPrecision_rep_B_toDef = ReplicateOp_Divide.ToDefInit<Gamma>(this.CommonWeightPrecision_F);
			this.CommonWeightPrecision_rep_F_marginal = ReplicateOp_Divide.Marginal<Gamma>(this.CommonWeightPrecision_rep_B_toDef, this.CommonWeightPrecision_F, this.CommonWeightPrecision_rep_F_marginal);
			this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isInitialised = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			this.vBernoulli5 = Bernoulli.Uniform();
			this.ModelSelector_marginal_F = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_B = new DistributionStructArray<Bernoulli,bool>(2);
			for(int _ind0 = 0; _ind0<2; _ind0++) {
				this.ModelSelector_selector_cases_B[_ind0] = Bernoulli.Uniform();
			}
			this.ModelSelector_selector_cases_0_uses_B = new Bernoulli[55];
			this.ModelSelector_selector_cases_0_uses_B[53] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[52] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[51] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[50] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[49] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[48] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[47] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[45] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[44] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[43] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[40] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[38] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[36] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[35] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[32] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[31] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[30] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[29] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[28] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[27] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[23] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[20] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[18] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[17] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[16] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[14] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[13] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[12] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[11] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[10] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[9] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[8] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[7] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[6] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[5] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[4] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[3] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[2] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[1] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[0] = Bernoulli.Uniform();
			this.WeightPrecisionRates_depth0_uses_F = new DistributionStructArray<Gamma,double>[2];
			this.WeightPrecisionRates_depth0_uses_B = new DistributionStructArray<Gamma,double>[2];
			this.CommonWeightPrecision_F = GammaFromShapeAndRateOpBase.SampleAverageConditional(1.0, 1.0);
			this.Weights_uses_F = new DistributionStructArray<Gaussian,double>[2];
			this.Weights_uses_B = new DistributionStructArray<Gaussian,double>[2];
			this.ModelSelector_selector_cases_0_uses_B[15] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[19] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[21] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[22] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[24] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[25] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[26] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[33] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[34] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[37] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[39] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[41] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[42] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[46] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_uses_B[54] = Bernoulli.Uniform();
			this.ModelSelector_selector_cases_0_B = Bernoulli.Uniform();
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8_isDone = false;
					this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10_isDone = false;
					this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2_isDone = false;
					this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11_isDone = false;
				}
				this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12_isDone = false;
			}
			this.Constant();
			this.Changed_numberOfIterationsDecreased_Init_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_Ins8(initialise);
			this.Changed_InstanceCount();
			this.Changed_InstanceCount_InstanceFeatureCounts();
			this.Changed_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_Init_FeatureCount_FeatureInd10(initialise);
			this.Changed_FeatureValues_InstanceCount_InstanceFeatureCounts();
			this.Changed_FeatureCount();
			this.Changed_FeatureCount_WeightConstraints();
			this.Changed_FeatureCount_WeightPrecisionRateConstraints();
			this.Changed_FeatureCount_ZeroFeatureValueInstanceCounts();
			this.Changed_FeatureCount_numberOfIterationsDecreased_Init_FeatureIndexes_FeatureValues_InstanceCount_Ins2(initialise);
			this.Changed_FeatureCount_FeatureIndexes_InstanceCount_InstanceFeatureCounts_numberOfIterationsDecreased_11(initialise);
			this.Changed_FeatureCount_FeatureIndexes_FeatureValues_InstanceCount_InstanceFeatureCounts_Labels_numberO12(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="InstanceCount") {
				return this.InstanceCount;
			}
			if (variableName=="FeatureCount") {
				return this.FeatureCount;
			}
			if (variableName=="InstanceFeatureCounts") {
				return this.InstanceFeatureCounts;
			}
			if (variableName=="FeatureValues") {
				return this.FeatureValues;
			}
			if (variableName=="FeatureIndexes") {
				return this.FeatureIndexes;
			}
			if (variableName=="WeightConstraints") {
				return this.WeightConstraints;
			}
			if (variableName=="WeightPrecisionRateConstraints") {
				return this.WeightPrecisionRateConstraints;
			}
			if (variableName=="ZeroFeatureValueInstanceCounts") {
				return this.ZeroFeatureValueInstanceCounts;
			}
			if (variableName=="Labels") {
				return this.Labels;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="ModelSelector") {
				return this.ModelSelectorMarginal();
			}
			if (variableName=="Weights") {
				return this.WeightsMarginal();
			}
			if (variableName=="WeightPrecisionRates") {
				return this.WeightPrecisionRatesMarginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			if ((variableName=="Weights")&&(query=="MarginalDividedByPrior")) {
				return this.WeightsMarginalDividedByPrior();
			}
			if ((variableName=="WeightPrecisionRates")&&(query=="MarginalDividedByPrior")) {
				return this.WeightPrecisionRatesMarginalDividedByPrior();
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		/// <summary>
		/// Returns the marginal distribution for 'ModelSelector' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli ModelSelectorMarginal()
		{
			return this.ModelSelector_marginal_F;
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="InstanceCount") {
				this.InstanceCount = (int)value;
				return ;
			}
			if (variableName=="FeatureCount") {
				this.FeatureCount = (int)value;
				return ;
			}
			if (variableName=="InstanceFeatureCounts") {
				this.InstanceFeatureCounts = (int[])value;
				return ;
			}
			if (variableName=="FeatureValues") {
				this.FeatureValues = (double[][])value;
				return ;
			}
			if (variableName=="FeatureIndexes") {
				this.FeatureIndexes = (int[][])value;
				return ;
			}
			if (variableName=="WeightConstraints") {
				this.WeightConstraints = (DistributionStructArray<Gaussian,double>)value;
				return ;
			}
			if (variableName=="WeightPrecisionRateConstraints") {
				this.WeightPrecisionRateConstraints = (DistributionStructArray<Gamma,double>)value;
				return ;
			}
			if (variableName=="ZeroFeatureValueInstanceCounts") {
				this.ZeroFeatureValueInstanceCounts = (double[])value;
				return ;
			}
			if (variableName=="Labels") {
				this.Labels = (bool[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'WeightPrecisionRates' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gamma,double> WeightPrecisionRatesMarginal()
		{
			return this.WeightPrecisionRates_marginal_F;
		}

		/// <summary>
		/// Returns the output message (the posterior divided by the prior) for 'WeightPrecisionRates' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The output message (the posterior divided by the prior)</returns>
		public DistributionStructArray<Gamma,double> WeightPrecisionRatesMarginalDividedByPrior()
		{
			return this.WeightPrecisionRates_use_B;
		}

		/// <summary>
		/// Returns the marginal distribution for 'Weights' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> WeightsMarginal()
		{
			return this.Weights_marginal_F;
		}

		/// <summary>
		/// Returns the output message (the posterior divided by the prior) for 'Weights' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The output message (the posterior divided by the prior)</returns>
		public DistributionStructArray<Gaussian,double> WeightsMarginalDividedByPrior()
		{
			return this.Weights_B;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
